---
title: "Reproducible Research Tools and Practices"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: true
editor_options:
  chunk_output_type: console
---

## Introduction

The aim of this website is to give an overview of several tools for reproducible statistical and data science research. Many of these tools will also help with workflow, organization, productivity, and your general sense of peace and well being as you go about your work. 

Here are some caveats before we get going: 

+ This is not an exhaustive list. If you have something that you use and like I would love to know about it and add it in. Feel free to open a [GitHub Issue](https://github.com/jean997/rr_tools/issues) and let me know about it!
+ This website doesn't attempt to give thorough tutorials. It is more of an aggregation of useful things that have already been well documented others elsewhere. I'll do my best to supply all the links you need to get going with each thing. Please let me know if you find a broken link of if you've found something useful you want to add.
+ I am mostly an R user so some of these tools are fairly R focused but in a lot of cases similar principles apply across languages. 

This website was built using `workflowr` which is covered in the section on [Workbooks and Reports](workbooks.html).

[Here](2020-10-24_reproducibility_bbag.pptx) is a set of slides that cover the material here. 

## What is Reproducibility?

Reproducibility has to do with regenerating results that are reported in scientific literature. 
There are different ways that results might be regenerated which mean different things about the reliability of the result. We say that:

The result is **repeatable** if the original investigators can regenerate published results from the original data. 

The result is **reproducible** if different investigators can regenerate the results, potentially using materials and instructions obtained from the original investigators. 

The result is **replicable** if new investigators can reach the same conclusions from a new experiment/sample.

Scientific integrity requires us to pay attention to ensuring all three of these features. Here we are focusing on technical tools and practices that help guarantee repeatability and reproducibility. We won't address errors in experimental design or data collection. 


## What Does Reproducible Statistical Research Look Like?

Some results may be nominally reproducible in that authors promise "code and data on reasonable request" but how often can these results actually be reproduced? According to [Minocher et al](https://psyarxiv.com/4nzc7/) not as often as we would like! What can you do to make sure your results are easily reproducible and you are not scrambling if someone asks you for the results years later?

+ Code is publicly available and well documented.
+ Data is publicly available if possible. 
+ Code can be run on a reasonable range of computing systems. 
+ Analysis is well documented enough that it can be run by another without help from the authors. 


## Effort, Pain, and Learning Curves

Each step that you take towards reproducibility will require some modification of your work habits. It is natural to work initially in ways that turn out later to be messy and hard to recreate. This is why it is so common for people to lose files or send the wrong version of something. Learning new tools, installing software, and creating new habits all take up time and can be awkward and uncomfortable. The payoff is in fewer headaches down the road and confidence in the results you report or publish on. 

Developing your work habits and your programming skills is an ongoing project. I organized the content below into categories that are about the order that I have adopted different habits but fee free to hop around. 



## Content

1. [File Names and Directory Structure](file_org.html)
1. [Version Control (Git)](version_control.html)
    + Git
1. [Code and Programming Practices](programming.html)
    + Data processing practices
    + Programming tips
1. [Workbooks and Reports](workbooks.html)
    + R Markdown and Sweave with `knitr`
    + `workflowr` for project organization
    + Software environments
1. [Pipelines](pipelines.html)
    + Snakemake
    + DSC for simulations


## Resources

[A Good Talk](https://www.youtube.com/watch?v=zwRdO9_GGhY&t=2s) by Richard McElreath

[Advanced R Book](http://adv-r.had.co.nz/) by Hadley Wickham

[R Packages Book](https://r-pkgs.org/) by Hadley Wickham

[Efficient R](https://csgillespie.github.io/efficientR) by Collin Gillespe and Robin Lovelace

[Happy Git with R](https://happygitwithr.com/) by Jenny Bryan

[R Markdown Cookbook](https://bookdown.org/yihui/rmarkdown-cookbook/) by Yihui Xie, Christophe Dervieux, and Emily Riederer

[Conda](https://docs.conda.io/projects/conda/en/latest/)

[`workflowr`](https://jdblischak.github.io/workflowr/) developed by John Blischak

[Snakemake](https://snakemake.readthedocs.io/en/stable/) 

[DSC](https://stephenslab.github.io/dsc-wiki/overview)
